name: risatonnet
description: A new Flutter project.
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
